### PR TITLE
Adding GraphDB documents

### PR DESCRIPTION
**Pull request by msadjad**
Add the documentation on the GraphDB to the repository

### CODE REVIEW

**Review by renannprado — CHANGES_REQUESTED** [review]
Minor: just remove the .ds_store file

**Comment by msadjad** [comment]
Oh, sure, didn't see that. I will and add it to the .gitignore :-D Thanks for mentioning it @renannprado

**Review by FD-HH — APPROVED** [review]
Awesome! 🚀

**Comment by msadjad** [comment]
@renannprado I removed it but in order to remove it entirely from history, I pushed forced it.

**Pull request merged**
